### ISSUE TITLE
用UPTIME监测服务，该如何设置？

### ISSUE THREAD

**Issue by Java2Boy** [wy580477/replit-trojan#14]
服务目前被限速，经常失联，起用uptime监测，如何设置保证服务在线？

**Comment by wy580477** [comment]
> 服务目前被限速，经常失联，起用uptime监测，如何设置保证服务在线？

去uptimerobot注册一个账户就行，新建一个https类型监测

![image](https://user-images.githubusercontent.com/98247050/217140126-ec9fa8cd-49fc-4c4d-8315-aba38391134f.png)

由于会返回404，所以会显示down，不用理它。

**Comment by Java2Boy** [comment]
感谢，从本地Docker上搭了个uptime,主要是参数设置不太懂，以为是没起作用
