### ISSUE TITLE
被平台封了

### ISSUE THREAD

**Issue by cy920820** [wy580477/replit-trojan#15]

**Comment by wy580477** [comment]
兄弟还能再言简意赅点么，五个字就完事了，一点描述和截图都没有。

**Comment by cy920820** [comment]
![image](https://user-images.githubusercontent.com/21211512/218035463-fdbcfe7b-c129-49e5-ab30-2e551b2385fd.png)

**Comment by cy920820** [comment]
估计得重新建了，然后低调点，一些敏感信息得干掉了吧 @wy580477

**Comment by wy580477** [comment]
> 估计得重新建了，然后低调点，一些敏感信息得干掉了吧 @wy580477

不用。先fork，然后去setting里面，打开Template repository，按模板建一个新库就能部署。

比如你的新库名字是 test/test123

访问 https://repl.it/github/test/test123 ，就可以部署。

**Comment by cy920820** [comment]
> > 估计得重新建了，然后低调点，一些敏感信息得干掉了吧 @wy580477
> 
> 不用。先fork，然后去setting里面，打开Template repository，按模板建一个新库就能部署。
> 
> 比如你的新库名字是 test/test123
> 
> 访问 https://repl.it/github/test/test123 ，就可以部署。
> 
> 和 Heroku 一样，只是屏蔽了 github 库地址和下游所有的 fork，并没有做代码审查。

刚发现这种方式也被平台检测到了，是不是被彻底打死了

**Comment by wy580477** [comment]
> 刚发现这种方式也被平台检测到了，是不是被彻底打死了

换 sing-box 核心了，你再试下看看。

**Comment by cy920820** [comment]
![image](https://user-images.githubusercontent.com/21211512/236608823-218c9d0b-8bfd-44f1-b99d-d1f357ee49c0.png)


> > 刚发现这种方式也被平台检测到了，是不是被彻底打死了
> 
> 换 sing-box 核心了，你再试下看看。

不知道是什么原因，import github 之后，就一直卡在这里了

**Comment by cy920820** [comment]
手动删除蒙层的 DOM 之后，运行还是会报错 
![image](https://user-images.githubusercontent.com/21211512/236608984-05eea0bf-b404-4479-9017-cc03f8722965.png)

**Comment by wy580477** [comment]
> 手动删除蒙层的 DOM 之后，运行还是会报错

我也不知道导入出啥问题了。  

下载回去以后，解压，把 readme 以外的文件上传进 bash 模板 repl:
https://codeload.github.com/wy580477/replit-trojan/zip/refs/heads/main

**Comment by cy920820** [comment]
> > 手动删除蒙层的 DOM 之后，运行还是会报错
> 
> 我也不知道导入出啥问题了。
> 
> 下载回去以后，解压，把 readme 以外的文件上传进 bash 模板 repl: https://codeload.github.com/wy580477/replit-trojan/zip/refs/heads/main

大佬牛逼，看来文件内容的敏感关键字都一并检测
