### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by 8ty** [wy580477/replit-trojan#5]
按照步骤来的，然后扫描二维码应该不会出现填错配置的问题

**Comment by 8ty** [comment]
网站可以正常打开

**Comment by wy580477** [comment]
> 按照步骤来的，然后扫描二维码应该不会出现填错配置的问题

是不是旧款安卓设备，证书得不到更新了，需要关掉证书验证。

**Comment by 8ty** [comment]
> > 按照步骤来的，然后扫描二维码应该不会出现填错配置的问题
> 
> 是不是旧款安卓设备，证书得不到更新了，需要关掉证书验证。

可能是，换了个设备和最新版本的app就行了
