### ISSUE TITLE
macos 使用 v2rayU 连接之后无法正常访问

### ISSUE THREAD

**Issue by cy920820** [wy580477/replit-trojan#6]

**Comment by cy920820** [comment]
![image](https://user-images.githubusercontent.com/21211512/208645718-db55c7a8-9040-487b-8b66-d74b1e0d826f.png)

**Comment by cy920820** [comment]
![image](https://user-images.githubusercontent.com/21211512/208645814-933e3428-69e5-4696-a402-aed628b6d8d6.png)

**Comment by wy580477** [comment]
有没有客户端日志，贴一下。

**Comment by cy920820** [comment]
![image](https://user-images.githubusercontent.com/21211512/208663401-5042419e-5e06-4eeb-bf13-f6ed88b3d8c2.png)

**Comment by wy580477** [comment]
日志看起来没问题啊。打开网页报什么错。

**Comment by cy920820** [comment]
> 日志看起来没问题啊。打开网页报什么错。

访问不了，没有网络

**Comment by wy580477** [comment]
> > 日志看起来没问题啊。打开网页报什么错。
> 
> 访问不了，没有网络

试一下其它客户端，如果正常那就可能是v2rayU的问题了。

**Comment by wy580477** [comment]
> 其他客户端也是，不能正常访问

换个网络环境呢，用手机流量试试？

**Comment by cy920820** [comment]
> > 其他客户端也是，不能正常访问
> 
> 换个网络环境呢，用手机流量试试？
> 
> 如果还是一样，可能客户端设置填写有误？
> 
> 我也没啥好想法。

手机流量确实可以

**Comment by cy920820** [comment]
> 我用v2rayx 1.5.1可以用，不过设置是在configure里的import导入由安卓中matsuri正常使用导出的json文件。导入后要在advanced的outbounds中删除direct项。然后finish,然后删除本身自带的test sever，然后再下载v2ray-core mac64包，适合的包最新版本为v2ray-core 4.31.0,下载后放入v2rayx的用户目录 /users/xxx/library/application support/v2rayx/v2ray-croe。最后点load core，模式选global mode就可以用了，也可以用pac mode模式，不过在OSX上要安装node。这个软件的github主页上有关于制作最新的pac.js的用法。node update_pac.js。就生成最新的pac.js,然后放入v2rayx的用户目录/users/xxx/library/application support/v2rayx/pac就行了。装这个软件只为replit用。其他的还是v2rayu好用。

还是没搞定， 没有安卓机，无法使用 matsuri 导出的 json，用小飞机的json 发现解析失败
